import firebase from 'react-native-firebase';

import {NotificationsAndroid} from 'react-native-notifications';

class NotificationsService {

    notificationListener = null;

    createLocalNotification = (title, body, fireDate = new Date()) => {
        const notification = new firebase.notifications.Notification()
        .android.setChannelId('testchannel')
        .setTitle(title)
        .setBody(body)
        .android.setSmallIcon('ic_notification')
        .android.setLargeIcon('ic_notification');

        // Schedule the notification for 1 minute in the future
        // const date = new Date();
        // date.setMinutes(date.getMinutes() + 1);a

        firebase.notifications().scheduleNotification(notification, {
            fireDate: fireDate.getTime(),
        });
    }

    unlistenNotifications = () => async (dispatch, getState) => {
        if(this.notificationListener) {
            this.notificationListener();
            this.notificationListener = null;
        }
    }

    listenNotifications = () => async (dispatch, getState) => {
        const state = getState();
        const { user } = state;
        console.log('ARA AY', this.notificationListener);
        this.unlistenNotifications();
        
        if(!user.Id){
            return;
        }
        try {
            // const notifications = await response.json().catch(error => { throw error });
            // if(notifications.Message) { return Promise.reject(new Error(data.Message)) }
            // const mappedNotifs = notifications.map(notif => ({
            //     ...notif,
            //     title : '',
            //     description : notif.notif_mess,
            // }));
            
            // dispatch(NotificationsActions.setNotifications(mappedNotifs));

            this.notificationListener = firebase.firestore()
                .collection('Users')
                .doc(user.Id)
                .collection('Notifications')
                .where("Status","==","Unread")
                .onSnapshot(notification => {
                    const notifs = notification.docs.map(data => data.data());

                    console.log('BAGO NOTIF',notifs);
                    // const userData = user.data();
                    // dispatch(UserAction.setUser(userData));
                    console.log('AHSSASAS');
        // NotificationsAndroid.localNotification({
        //     title: "Local notification",
        //     body: "This notification was generated by the app!",
        //     extra: "data",
        //     "google.message_id": ""
        // });
        // alert('Ayyy');
                })
        } catch(err) {
        }

    };
}

export default new NotificationsService();
